---

- name: Check if Cargo is installed
  shell: |
    test -f ~/.cargo/env && . ~/.cargo/env && command -v cargo
  become_user: rylev
  register: cargo_exists
  changed_when: cargo_exists.rc == 1
  failed_when: cargo_exists.rc > 1

- name: Download installer
  when: cargo_exists is changed
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: '0755'
    force: 'yes'

- name: Install Rust/Cargo
  when: cargo_exists is changed
  shell: /tmp/sh.rustup.rs -y
  become_user: rylev

- name: Install cargo binaries
  include_tasks: "cargo_install.yml"
  loop:
     - cargo-expand
     - cargo-sweep
     - cargo-outdated
     - tokei
     - fclones
     - jql
     - choose
