---

# SSH server configuration

- name: Install SSH Server
  apt:
    pkg: openssh-server
    state: latest

- name: Allow password authentication"
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: PasswordAuthentication yes
    state: present

- name: Allow root SSH access
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: PermitRootLogin yes
    state: present

- name: Ensure sshd is started
  service:
    name: ssh
    state: started
    enabled: true

# SSH client configuration

- name: Create .ssh directory
  file:
    path: ~/.ssh
    state: directory
    mode: '0700'

- name: Generate key pair
  openssh_keypair:
    path: ~/.ssh/id_ed25519
    type: ed25519
    owner: rylev
    group: rylev
    state: present
