---

- name: Check zsh installation
  shell: which zsh
  register: zsh
  changed_when: zsh.rc == 1
  failed_when: zsh.rc > 1

- name: Install zsh
  package:
    name: zsh
  when: zsh.rc != 0

- name: Find current default shell
  shell: sudo grep "^${USER}.*zsh$" /etc/passwd
  become_user: rylev
  register: default_shell
  changed_when: default_shell.rc == 1
  failed_when: default_shell.rc > 1

- name: Make default shell
  shell: chsh -s $(which zsh)
  when: default_shell.rc == 1

- name: Check if .oh-my-zsh installed
  stat:
    path: "{{ ansible_env.HOME }}/.oh-my-zsh"
  become_user: rylev
  become: true
  register: oh_my_zsh

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  become_user: rylev
  when: not oh_my_zsh.stat.exists

- name: Configure zsh
  template:
    src: zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"

- name: ensures .zsh dir exists
  file:
    path: "{{ ansible_env.HOME }}/.zsh"
    state: directory

- name: Configure zsh config
  template:
    src: config
    dest: "{{ ansible_env.HOME }}/.zsh/config"

- name: Configure zsh env
  template:
    src: env
    dest: "{{ ansible_env.HOME }}/.zsh/env"

- name: Configure zsh aliases
  template:
    src: aliases
    dest: "{{ ansible_env.HOME }}/.zsh/aliases"
