---

- name: Set a hostname
  hostname:
    name: milton

- name: Update apt-get repo and cache
  become: true
  apt:
    update_cache: yes

- name: Install common packages
  become: true
  package:
    name:
     - htop
     - ncdu
     - build-essential
     - cmake
     - libssl-dev
     - pkg-config
     - awscli
     - bat
     - exa
     - vim
     - xclip
     - fd-find
     - ripgrep
     - peco
     - cifs-utils        # mounting fileshares
     - nmap              # mapping networks
     - flatpak
     - anacron
     - nala
    state: latest

# bat is installed as batcat in apt
- name: Create bat alias for batcat
  file:
    src: /usr/bin/batcat
    dest: /usr/bin/bat
    state: link

# fd is installed as fdfind in apt
- name: Create fd alias for fdfind
  file:
    src: /usr/bin/fdfind
    dest: /usr/bin/fd
    state: link
