# Load Configuration Files

dotdir="$HOME/Code/personal/dotfiles"
zshdir="$dotdir/zsh"

for file in ${zshdir}/{config,env,personal,functions,aliases};
do
  [ -r "$file" ] && source "$file"
done

# Path modifications
export PATH="/usr/local/bin:~/.nvm:${PATH}"

# nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
