---

- name: Add key for the 1Password apt repo
  apt_key:
    url: https://downloads.1password.com/linux/keys/1password.asc
    state: present

- name: Add 1Password apt repo
  apt_repository:
    filename: 1password
    repo: "deb https://downloads.1password.com/linux/debian/amd64 stable main"
    state: present

- name: Install 1Password
  apt:
    pkg: 1password
    state: present
